### ISSUE TITLE
符号重叠

### ISSUE THREAD

**Issue by hugh1927** [Buernia/Noto-SHS-Magisk-module#10]
![S30401-19053591](https://user-images.githubusercontent.com/61912504/229285131-f72e0144-66ac-43ba-95be-26eb1026c917.png)
这是数字符号，1234背景是蓝色的那种，似乎重叠，我卸载了手机其他自己测了好几次都这样，仅建议，谢谢您的模块

**Comment by Buernia** [comment]
图案数字符号0️⃣—🔟实际上是由普通数字和组合记号 `⃣` 结合而成，显示情况因字体和排版引擎而异。在支持较差的情况下可能不会显示成组合好的图案字形。

**Comment by hugh1927** [comment]
明白了谢谢
