### ISSUE TITLE
最完美的miui13模块字体

### ISSUE THREAD

**Issue by guobaoqiang1** [Buernia/Noto-SHS-Magisk-module#3]
我的miui13完美，全局应用了，很好，唯一一个不用空字体模块的。大佬能多做几个字体吗？像什么筑紫黑，筑紫圆。或者能分享你的字体模板吗？能去´_>`酷安发帖吗？英文认识的很少。

**Comment by Buernia** [comment]
一般的商业字体满足不了我个人对多语言多风格多字重的需求，所以我不会再做更多的模块。
至于模板，可以参考酷安上[W乡村小鱼的模块](https://www.coolapk.com/feed/37296346?shareKey=NjE1MThmMmMwZDQ3NjMyOTA5ZGM~)，这个也不需要空字体模块，更适合一般的非可变字体。
