### ISSUE TITLE
如何替换彩色表情文字为手机自带？

### ISSUE THREAD

**Issue by guobaoqiang1** [Buernia/Noto-SHS-Magisk-module#4]
想把绘文字（emoji）字体替换为系统的，和自带的显示有些违和。自己直接删除NotoColorEmojiFlags.ttf，NotoColorEmoji.ttf。直接不显示了。彩色表情现在显示的口口。要在xml里删除配置信息吗？

**Comment by Buernia** [comment]
本模块会整体替换系统字体文件夹，不留原生字体，直接删除字体会导致缺字。
用原版 NotoColorEmoji.ttf 替换模块字体文件夹里的同名字体即可恢复原版绘文字（emoji）。
NotoColorEmojiFlags.ttf 用于显示旗帜，仍是原版字体，无需修改。
