### ISSUE TITLE
等一个其它黑体，思源黑体实在字形不咋的

### ISSUE THREAD

**Issue by guobaoqiang1** [Buernia/Noto-SHS-Magisk-module#5]
期待大佬做个其它字体的，比如悠黑，兰亭等等，这个思源黑体字形实在不好看啊

**Comment by Buernia** [comment]
抱歉，目前没有这个打算。
思源黑体在字形设计上并非最优，但在字符数量和中日韩语言支持方面，思源黑体是唯一的选择。
