### ISSUE TITLE
MIUI14完美可用，不需要空字体模块

### ISSUE THREAD

**Issue by hwitdew** [Buernia/Noto-SHS-Magisk-module#7]
miui14完全没问题，如果能粗一点就好了

**Comment by xianax** [comment]
又重新试了下，没有空字体模块的话本模块不生效，另外就是完全相同的设置下bug又消失了，可能是miui本身的bug，结论是miui14也可以，相当不错

**Comment by Buernia** [comment]
了解，感谢测试。

**Comment by Croakero** [comment]
MIUI14 EU14.0.9.0.TLDCNXM 完全正常，我也觉得有点细
